server:
  port: 9092
camunda:
  bpm:
    default-serialization-format: application/json
    admin-user:
      id: admin
      password: admin
      email: admin@admin.org
      first-name: Admin
      last-name: Administratos
    history-level: activity
spring:
  jpa:
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

axon:
  camunda:
    send-signals: false
  axonserver:
    enabled: false
